FROM registry.access.redhat.com/ubi8/graalvm-ce:java17-22.3 as build

WORKDIR /app

COPY . .

RUN gu install native-image
RUN mvn clean package -Dnative -DskipTests || exit 1

FROM gcr.io/distroless/java17-debian11

COPY --from=build /app/target/quarkus-app-native-image-* /app/

EXPOSE 8080

ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

ENTRYPOINT ["/app/quarkus-app-native-image-*"]