FROM maven:3.8.3-openjdk-11 as build

WORKDIR /app

COPY . .

RUN mvn clean package -DskipTests || exit 1

FROM openjdk:11-jre-slim

WORKDIR /app

RUN groupadd -r -g 185 quarkus && useradd -r -u 185 -g quarkus -ms /bin/sh quarkus

COPY --chown=185:185 --from=build /app/target/quarkus-app/quarkus-run.jar /app/

EXPOSE 8080

ENV JAVA_OPTS_APPEND="-Dquarkus.http.host=0.0.0.0 -Djava.util.logging.manager=org.jboss.logmanager.LogManager"

ENTRYPOINT ["java", "-jar", "/app/quarkus-run.jar"]